### PR TITLE
add setIcon  function for Windows

### PR DESCRIPTION
**Pull request by ItoYo16u**
I'm adding `setIcon` function for Windows.

- [x] set icon by specifying file name for debug
- [x]  set icon by File
- [ ]  ~~set icon by bytes~~

### CODE REVIEW

**Comment by ItoYo16u** [comment]
jfx
- https://github.com/openjdk/jfx/blob/86b854dc367fb32743810716da5583f7d59208f8/modules/javafx.graphics/src/main/native-glass/win/Pixels.cpp#L105

**Comment by ItoYo16u** [comment]
https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/icon.rs

**Comment by tonsky** [comment]
Let’s postpone “set icon by bytes” to another PR. I’m not sure we want to bring bitmaps and encoder/decoder to the codebase. Loading from file should be enough for now.

Can you please resolve current conflicts and add dummy `setIcon` implementations for WindowX11.java and WindowMac.java? Just simple

```
@Override
public Window setIcon(File path) {
  // TODO #95
  return this;
}
```

So that they continue to compile?
Thanks!

**Comment by tonsky** [comment]
And thank you for your contribution, that’s pretty substantial and an imporant feature.

**Comment by ItoYo16u** [comment]
Thank you for reviewing and I fixed conflicts.

**Comment by tonsky** [comment]
Awesome, merged! Thank you

**Pull request merged**
