### PR TITLE
Setup basic root cmake file (for clion project import)

### PR DESCRIPTION
**Pull request by EgorOrachyov**
#7  It looks kinda weired for now since it has no complex logic, mb in the future we will extend it

### CODE REVIEW

**Comment by EgorOrachyov** [comment]
@tonsky @SergeevPavel what do you think?

**Comment by EgorOrachyov** [comment]
CMAKE_SOURCE_DIR won't work in macos end etc., if add this folders as subdirs, since
when root cmake is ...../JWM/CMakeLists.txt => CMAKE_SOURCE_DIR  = ..../JWM, and not ..../JWM/macos

**Comment by EgorOrachyov** [comment]
I'll replace CMAKE_SOURCE_DIR  with CMAKE_CURRENT_LIST_DIR (must work exactly the same way)

**Comment by SergeevPavel** [comment]
works for me! thanks

**Pull request merged**
